project:
  type: website

website:
  page-footer: "Copyright 2024 @ IIT Madras"
  page-navigation: true
  navbar: 
    pinned: true
    logo: "/assets/images/logo.png"
    left:
      - text: "Home"
        file: index.md
      - text: "PPAs"
        file: ppa.md
      - text: "How to"
        file: howto.md
      - text: "FAQs"
        file: faq.md
      - text: "Student Corner"
        file: students.md
      - text: "About"
        file: about.md
      - text: "Feedback"
        file: feedback.md

  sidebar:
    - title: "PPAs"
      collapse-level: 1
      border: true
      foreground: "primary"
      contents:
        - ppa.md
        - auto: ppa/week-1
        - auto: ppa/week-2
        - auto: ppa/week-3
        - auto: ppa/week-4
        - auto: ppa/week-5
        - auto: ppa/week-6

    - title: "How to"
      collapse-level: 1
      border: true
      foreground: "primary"
      contents:
        - howto.md
        - auto: howto/topic/*

    - title: "Presentations"
      collapse-level: 1
      border: true
      foreground: "primary"
      contents:
        - presentations.md
        - presentations/week-1.qmd



format:
  html:
    theme: 
      light: [cosmo, theme.scss]
    fontsize: 20px
    toc: true
    grid:
      sidebar-width: 200px
      margin-width: 300px
      body-width: 800px  
    code-line-numbers: true
    highlight-style: github
    code-block-border-left: "#D3D3D3"
    code-overflow: scroll
    css: styles.css
    include-in-header:
      - text: |
          <!-- Appzi: Capture Insightful Feedback -->
          <script async src="https://w.appzi.io/w.js?token=AHdPu"></script>
          <!-- End Appzi -->
